---
  - name: Load Primary specific vars
    include_vars: primary.yml

  - name: Add per domain directory for Primary zones. including keys dir.
    file:
      path: "{{ datapath }}/pri/{{ item.name }}/keys"
      state: directory
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: 0770
    loop: "{{ pri_domains }}"

  - name: Add TSIG files if not present. Existing files will not be overwritten!
    include_tasks: tsig_generation.yml
    loop: "{{ tsig_files }}"
    loop_control:
      loop_var: tsig_name

  - name: Add Primary domain zone files if not present
    template:
      src: "{{ lookup('first_found', zone_files ) }}"
      dest: "{{ datapath }}/pri/{{ item.name }}/{{ item.name }}.db"
      force: "{{ 'yes' if item.zonetype == 'static' else 'no' }}"
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: 0660
    vars:
      zone_files:
        files:
          - "{{ item.name }}.db.j2"
          - "{{ item.zonetype }}.db.j2"
          - default.db.j2
        paths:
          - "{{ zone_file_path }}"
          - 'templates'
    loop: "{{ pri_domains }}"
    notify: reload isc-bind scl
    register: zone_changes


  - name: Static Zone file changes will cause new serial to be written
    template:
      src: serial.j2
      dest: "{{ datapath }}/pri/{{ domain.item.name }}/{{ domain.item.name }}.serial"
      force: yes
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: 0660
    when: domain.changed == true
    loop: "{{ zone_changes.results}}"
    loop_control:
      loop_var: domain
      label: domain.item.name


  - name: Copy Zone statement files for primary domains
    template:
      src: "{{ lookup('first_found', zone_statement) }}"
      dest: "{{ confpath }}/{{ item.name }}.zone.conf"
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      backup: yes
      mode: 0660
    vars:
      zone_statement:
        files:
          - "{{ item.name }}.zone.j2"
          - simple.zone.j2
        paths:
          - "{{ zone_file_path }}"
          - 'templates'
    loop: "{{ pri_domains }}"
    notify: reconfig isc-bind scl
