---
  - name: Is the tsig file present locally?
    become: no
    find:
      paths: "{{ shared_file_path }}/"
      pattern: "{{ tsig_name }}.tsig"
      file_type: file
    register: tsig_local
    delegate_to: localhost
    tags:
      - tsig
  - name: If found, copy local tsig file to remote host. Will overwrite if different.
    copy:
      src: "{{ shared_file_path }}/{{ tsig_name }}.tsig"
      dest: "{{ confpath }}/{{ tsig_name }}.tsig"
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: '0660'
      backup: yes
    notify: reconfig isc-bind scl
    when:
      - tsig_local.matched > 0

  - name: Is the tsig file present on remote?
    find:
      paths: "{{ confpath }}/"
      pattern: "{{ tsig_name }}.tsig"
      file_type: file
    register: tsig_found
    tags:
      - tsig
  - name: If present on remote, but not local, then fetch.
    fetch:
      src: "{{ confpath }}/{{ tsig_name }}.tsig"
      dest: "{{ shared_file_path }}/{{ tsig_name }}.tsig"
      flat: yes
    when:
      - tsig_local.matched == 0
      - tsig_found.matched > 0
  - name: No TSIG file present
    block:
    - name: Generate TSIG secret. Consider adding to Ansible Vault
      set_fact:
          tsig_pass: "{{ lookup('password','/dev/null', 'encrypt=argon2')|b64encode }}"
      tags:
        - tsig
        - secret
    - name: Copy TSIG template
      template:
        src: "{{ lookup('first_found', tsig_source) }}"
        dest: "{{ confpath }}/{{ tsig_name }}.tsig"
        owner: "{{ binduser }}"
        group: "{{ binduser }}"
        mode: 0660
      vars:
        tsig_source:
          files:
            - "{{ tsig_name }}.tsig"
            - tsig_template.j2
          paths:
            - "{{ zone_file_path }}"
            - 'templates'
      notify: reconfig isc-bind scl
    - name: Place the generated TSIG file on server for distribution
      fetch:
        src: "{{ confpath }}/{{ tsig_name }}.tsig"
        dest: "{{ shared_file_path }}/"
        flat: yes
    when:
      - tsig_found.matched == 0
