---
  - name: restart isc-bind
    service:
      name: isc-bind-named
      state: restarted

  - name: reconfig isc-bind (Software Collection)
    shell: scl enable isc-bind -- rndc reconfig
    listen: "reconfig isc-bind scl"

  - name: reload isc-bind (Software Collection)
    shell: scl enable isc-bind -- rndc reload
    listen: "reload isc-bind scl"
