---
  - name: Install isc-bind repo from COPR
    yum_repository:
      name: "COPR-ISC-{{ BindRelease }}"
      description: COPR repo for BIND {{ BindRelease }} owned by ISC
      baseurl: "https://copr-be.cloud.fedoraproject.org/results/isc/{{ BindRelease }}/epel-{{ ansible_distribution_major_version }}-{{ ansible_userspace_architecture }}/"
      gpgkey: "https://copr-be.cloud.fedoraproject.org/results/isc/{{ BindRelease }}/pubkey.gpg"
      gpgcheck: yes
      skip_if_unavailable: yes
    #template: src=isc-bind-dev-epel-7.repo dest=/etc/yum.repos.d/isc-bind-dev-epel-7.repo
    tags: bind-repo
    # notify: yum-clean-metadata
    # uncomment notify if repo is removed 'state: absent'

  - name: Install isc-bind
    yum:
      name: isc-bind
      state: latest
    tags: isc-bind
# I should use a 'when' command to add master, slave or recursive
  - name: Configure BIND Config file
    template: src=named.conf.j2 dest=/etc/named.conf group=named
    tags: isc-bind
    notify: restart isc-bind

  - name: Add the conf directory
    file:
      path: /var/named/data/conf
      state: directory
      owner: named
      group: named
      mode: 0755

  - name: Start BIND
    service:
      name: isc-bind-named
      state: started
      enabled: yes
    tags: isc-bind
  # Add a conf directory for future config files to live in
