---
  - name: Install isc-bind repo from COPR
    yum_repository:
      name: "COPR-ISC-{{ BindRelease }}"
      description: COPR repo for BIND {{ BindRelease }} owned by ISC
      baseurl: "https://copr-be.cloud.fedoraproject.org/results/isc/{{ BindRelease }}/epel-{{ ansible_distribution_major_version }}-{{ ansible_userspace_architecture }}/"
      gpgkey: "https://copr-be.cloud.fedoraproject.org/results/isc/{{ BindRelease }}/pubkey.gpg"
      gpgcheck: yes
      skip_if_unavailable: yes
    tags: bind-repo
    # notify: yum-clean-metadata
    # uncomment notify if repo is removed 'state: absent'

  - name: Install isc-bind
    yum:
      name: isc-bind
      state: latest
    tags: isc-bind
#
  - name: create log directory
    file:
      path: "{{ logpath }}"
      state: directory
      group: "{{ binduser }}"
      mode: 0770

  - name: set paths for RHEL7
    set_fact:
      confpath: "{{ confpathrhel7 }}"
      datapath: "{{ datapathrhel7 }}"
    when:
      - ansible_facts['os_family'] == 'RedHat'
      - ansible_facts['distribution_major_version'] == "7"
  - name: set paths for RHEL8
    set_fact:
      confpath: "{{ confpathrhel8 }}"
      datapath: "{{ datapathrhel8 }}"
    when:
      - ansible_facts['os_family'] == 'RedHat'
      - ansible_facts['distribution_major_version'] == "8"

  - name: Configure BIND Config file
    template:
      src: "{{ ServerRole }}-named.conf.j2"
      dest: "{{ confpath }}/named.conf"
      group: named
      backup: yes
    tags: isc-bind
    notify: restart isc-bind

  - name: Start BIND
    service:
      name: isc-bind-named
      state: started
      enabled: yes
    tags: isc-bind

  - name: Make sure FirewallD allows DNS through (UDP amd TCP)
    firewalld:
      service: dns
      permanent: yes
      state: enabled
      immediate: yes
      zone: "{{ firewalldZone }}"
    when: ListenV4 != '' or ListenV6 != ''
