---
  - name: Install isc-bind repo from COPR
    yum_repository:
      name: "COPR-ISC-{{ BindRelease }}"
      description: COPR repo for BIND {{ BindRelease }} owned by ISC
      baseurl: "https://copr-be.cloud.fedoraproject.org/results/isc/{{ BindRelease }}/epel-{{ ansible_distribution_major_version }}-{{ ansible_userspace_architecture }}/"
      gpgkey: "https://copr-be.cloud.fedoraproject.org/results/isc/{{ BindRelease }}/pubkey.gpg"
      gpgcheck: yes
      skip_if_unavailable: yes

    tags: bind-repo
    # notify: yum-clean-metadata
    # uncomment notify if repo is removed 'state: absent'

  - name: Install isc-bind
    yum:
      name: isc-bind
      state: latest
    tags: isc-bind
#
  - name: set paths for RHEL7
    vars:
      confpath: "{{ confpathrhel7 }}"
      datapath: "{{ datapathrhel7 }}"
    when:
      - ansible_facts['os_family'] == 'RedHat'
      - ansible_facts['distribution_major_version'] == "7"
  - name: set paths for RHEL8
    vars:
      confpath: "{{ confpathrhel8 }}"
      datapath: "{{ datapathrhel8 }}"
    when:
      - ansible_facts['os_family'] == 'RedHat'
      - ansible_facts['distribution_major_version'] == "8"

  - name: Configure BIND Config file
    template:
      src: "{{ ServerRole }}-named.conf.j2"
      dest: "{{ confpath }}/named.conf"
      group: named
      backup: yes
    tags: isc-bind
    notify: restart isc-bind

  #- name: Add the conf directory
  #  file:
  #    path: /var/named/data/conf
  #    state: directory
  #    owner: named
  #    group: named
  #    mode: 0755

  - name: Start BIND
    service:
      name: isc-bind-named
      state: started
      enabled: yes
    tags: isc-bind
