---
  - name: Install isc-bind repo from COPR
    yum_repository:
      name: "COPR-ISC-{{ BindRelease }}"
      description: COPR repo for BIND {{ BindRelease }} owned by ISC
      baseurl: "https://copr-be.cloud.fedoraproject.org/results/isc/{{ BindRelease }}/epel-{{ ansible_distribution_major_version }}-{{ ansible_userspace_architecture }}/"
      gpgkey: "https://copr-be.cloud.fedoraproject.org/results/isc/{{ BindRelease }}/pubkey.gpg"
      gpgcheck: yes
      skip_if_unavailable: yes

    tags: bind-repo
    # notify: yum-clean-metadata
    # uncomment notify if repo is removed 'state: absent'

  - name: Install isc-bind
    yum:
      name: isc-bind
      state: latest
    tags: isc-bind
#
  - name: Configure BIND Config file for CentOS 7 (and lower)
    template:
      src: "{{ ServerRole }}-named.conf.j2"
      dest: /etc/opt/isc/isc-bind/named.conf group=named
      backup: yes
    when:
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "7"
    tags: isc-bind
    notify: restart isc-bind


  - name: Configure BIND Config file for CentOS 8
    template:
      src: "{{ ServerRole }}-named.conf.j2"
      dest: /etc/opt/isc/scls/isc-bind/named.conf group=named
      backup: yes
    when:
      - ansible_facts['distribution'] == "CentOS"
      - ansible_facts['distribution_major_version'] == "8"
    tags: isc-bind
    notify: restart isc-bind

  #- name: Add the conf directory
  #  file:
  #    path: /var/named/data/conf
  #    state: directory
  #    owner: named
  #    group: named
  #    mode: 0755

  - name: Start BIND
    service:
      name: isc-bind-named
      state: started
      enabled: yes
    tags: isc-bind
