---
  - name: Load Primary specific vars
    include_vars: primary.yml

  - name: Add per domain directory for Primary zones. including keys dir.
    file:
      path: "{{ datapath }}/pri/{{ item.name }}/keys"
      state: directory
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: 0770
    loop: "{{ pri_domains }}"


  - name: Add Primary domain zone files if not present
    template:
      src: "{{ lookup('first_found', zone_files ) }}"
      dest: "{{ datapath }}/pri/{{ item.name }}/{{ item.name }}.db"
      force: "{{ item.isstatic }}"
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: 0660
    vars:
      zone_files:
        files:
          - "{{ item.name }}.db.j2"
          - primary.db.j2
        paths:
          - 'templates'
    loop: "{{ pri_domains }}"
    notify: reload isc-bind scl
    register: zone_changes

  - debug:
      msg: "item.item={{item.item}}, item.changed={{item.changed}}"
    loop: "{{ zone_changes.results}}"

  - name: Static Zone file changes will cause new serial to be written
    template:
      src: serial.j2
      dest: "{{ datapath }}/pri/{{ domain.item.name }}/{{ domain.item.name }}.serial"
      force: yes
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: 0660
    when: "{{ item.changed == true }}"
    loop: "{{ zone_changes.results}}"
      loop_var: domain


  - name: Copy Zone statement files for dynamic primary domains
    template:
      src: "{{ lookup('first_found', zone_statement) }}"
      dest: "{{ confpath }}/{{ item.name }}.zone.conf"
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      backup: yes
      mode: 0660
    vars:
      zone_statement:
        files:
          - "{{ item.name }}.zone.j2"
          - local_signed_zone.j2
        paths:
          - 'templates'
    loop: "{{ pri_domains }}"
    notify: reconfig isc-bind scl
