---
  - name: Load Primary specific vars
    include_vars: primary.yml

  - name: Add per domain directory for Primary zones. including keys dir.
    file:
      path: "{{ datapath }}/pri/{{ item.name }}/keys"
      state: directory
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: 0770
    loop: "{{ pri_domains }}"


  - name: Add dynamic Primary domain zone files if not present
    template:
      src: "{{ lookup('first_found', [ '{{ item.name }}'.db.j2, primary.db.j2] ) }}"
      dest: "{{ datapath }}/pri/{{ item.name }}/{{ item.name }}.db"
      force: "{{ item.isstatic }}"
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      mode: 0660
    loop: "{{ pri_domains }}"


  - name: Copy Zone statement files for dynamic primary domains
    template:
      src: "{{ lookup('first_found', [ '{{ item.name }}'.zone.j2, local_signed_zone.j2] ) }}"
      dest: "{{ confpath }}/{{ item.name }}.zone.conf"
      owner: "{{ binduser }}"
      group: "{{ binduser }}"
      backup: yes
      mode: 0660
    loop: "{{ pri_domains }}"
